apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-static
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: "" # this should be empty becasue this is static
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-e8a95a42 # replace your filesystem Id

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-static
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi

# now attaching to pod by adding similar labels to sleect + this pod4
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    purpose: efs-static-demo
    project: roboshop
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:  # docker run -v host -v host-path:conatiner-path
    - name: persistent-storage
      mountPath: /usr/share/nginx/html
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: efs-static-demo

# service for connectimg ot from outside
---
apiVersion: v1
kind: Service
metadata:
  name: efs-static
  labels:
    purpose: efs-staic-demo
    project: roboshop

spec:
  type: LoadBalancer
  selector:
    purpose: efs-staic-demo
    project: roboshop
  ports:
    - protocol: TCP
      port: 80 # service port
      targetPort: 89 # container port
