apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-dynamic
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "efs-roboshop"
  resources:
    requests:
      storage: 5Gi

# now attaching to pod by adding similar labels to sleect + this pod4
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    purpose: efs-dynamic-demo
    project: roboshop
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:  # docker run -v host -v host-path:conatiner-path
    - name: persistent-storage
      mountPath: /usr/share/nginx/html
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: efs-static-demo

# service for connectimg ot from outside
---
apiVersion: v1
kind: Service
metadata:
  name: efs-dynamic
  labels:
    purpose: efs-dynamic-demo
    project: roboshop

spec:
  type: LoadBalancer
  selector:
    purpose: efs-dynamic-demo
    project: roboshop
  ports:
    - protocol: TCP
      port: 80 # service port
      targetPort: 89 # container port
---