apiVersion: v1
kind: Pod
metadata:
  name: multi-container
  labels:
    project: roboshop
    purpose: multi-container-demo
spec:
  containers:
    - name: nginx
    - name: nginx
    - name: almalinux
    - name: almalinux