apiVersion: v1
kind: Pod
metadata:
  name: multi-container
  labels:
    project: roboshop
    purpose: multi-container-demo
    component: mysql
    tier: backend
    environment: dev
spec:
  containers:
  - name: nginx
    image: nginx
