apiVersion: v1
kind: Pod
metadata:
  name: multi-container
  labels:
    project: roboshop
    purpose: multi-container-demo
    component: mysql
    tier: backend
    environment: dev
  annotations:
    description: "this is for annotations"
    docker: docker.io
spec:
  containers:
  - name: nginx
    image: nginx
