apiVersion: v1
kind: Pod
metadata:
  name: multi-container
  labels:
    project: roboshop
    purpose: multi-container-demo
    component: mysql
    tier: backend
    environment: dev
spec:
  containers:
  - name: nginx
    image: nginx
  resources:
    requests:
      memory: "64mi"
      cpu: "250m"
    limits:
      memory: "128mi"
      cpu: "4S00m"
