apiVersion: v1
kind: Pod
metadata:
  name: env-demo
  labels:
    project: roboshop
    purpose: demonstrate-envars
spec:
  containers:
    - name: nginx
      image: nginx
      env:
      - name: COURSE
        value: "KUBERNETES"
      - name: DEM0
        value: "block unwanted routes"